### ISSUE TITLE
Error while compile: crypto.hash is not a function

### ISSUE THREAD

**Issue by nallion** [cyan-2048/solid-telekram#1]
Please, help me ti resolve compiling error:

error during build:
TypeError: [kai-manifest] crypto.hash is not a function
    at Object.writeBundle (file:///home/nallion/solid-telekram-main/vite.config.ts.timestamp-1722800806811-95bada1efb417.mjs:155:113)
    at file:///home/nallion/solid-telekram-main/node_modules/rollup/dist/es/shared/node-entry.js:19774:40
    at async Promise.all (index 1)
    at async PluginDriver.hookParallel (file:///home/nallion/solid-telekram-main/node_modules/rollup/dist/es/shared/node-entry.js:19702:9)
    at async file:///home/nallion/solid-telekram-main/node_modules/rollup/dist/es/shared/node-entry.js:20699:13
    at async catchUnfinishedHookActions (file:///home/nallion/solid-telekram-main/node_modules/rollup/dist/es/shared/node-entry.js:20119:16)
    at async build (file:///home/nallion/solid-telekram-main/node_modules/vite/dist/node/chunks/dep-B8QpfTwU.js:67240:22)
    at async CAC.<anonymous> (file:///home/nallion/solid-telekram-main/node_modules/vite/dist/node/cli.js:842:9)
error: script "build" exited with code 1

![Снимок экрана от 2024-08-04 21-50-32](https://github.com/user-attachments/assets/34b0f046-743c-45e3-bb4b-485f217400c4)

**Comment by cyan-2048** [comment]
use latest node lts (node v20)
