### ISSUE TITLE
Clarification on enabling rlottie for GIF support

### ISSUE THREAD

**Issue by jazz-it** [cyan-2048/solid-telekram#3]
First, thank you for the great work on `solid-telekram`. I've encountered an issue while trying to enable `rlottie` for GIF-related functionality. It seems that the project has a dependency on `rlottie`, but since `rlottie` is not available as an NPM package, I couldn't install it via `npm install rlottie` on Windows 10. All other dependencies seem to work normally.

I attempted to clone the `rlottie` repository from [Samsung's GitHub page](https://github.com/Samsung/rlottie) and tried building it manually, but I’m unclear about how to properly integrate it into `solid-telekram`. As a result, features relying on `rlottie` (e.g., GIF support) don't seem to work as expected.

Questions:

1. What is the recommended way to install and configure `rlottie` for `solid-telekram`?
2. Should the `rlottie` dependency be added to `package.json` manually, or is there an alternative setup process?
3. Are there specific build steps required to ensure that GIF-related functionality is fully operational?

**Comment by cyan-2048** [comment]
Hi, the custom builds of rlottie is found in /src/lib/rlottie

yes I am using samsung's github page for the builds, I planned a while ago to create a guide on how to build for asm.js, however I was unable to find time for such documentation

a bit of heads up, it requires you to install an [older version of emscripten](https://github.com/emscripten-core/emscripten/issues/18013) for REAL asm.js

REAL asm.js means near native speeds for KaiOS 2.5

also if this issue is related to KaiOS 3.0, there is a problem with the wasm builds, it is using the wasm files from samsung's example builds which in turn uses eval for some reason, so using the asm.js version for rlottie should fix it.

LASTLY: rlottie has nothing to do with GIF support, it is used for the high quality vector stickers, GIF support on the app is a mix of a bunch of things (webm support, vp9/vp8 support, etc.)

**Comment by jazz-it** [comment]
Thank you for your heads up. I installed an older `emscripten`:

```
# get emsdk from git, then enter that directory
..
# get an older emsdk
git checkout 1.39.20
# get an older emscripten
./emsdk install 1.39.20-fastcomp
./emsdk activate 1.39.20-fastcomp
```

It came with older packages of `node` and `npm`, which results with:

<details>
  <summary>Command Prompt Output (Windows 10 Home / Visual Studio 2022)</summary>

```
>npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!

> esbuild@0.20.2 postinstall C:\Users\Me\Downloads\platform-tools\solid-telekram\node_modules\esbuild
> node install.js


> core-js@3.39.0 postinstall C:\Users\Me\Downloads\platform-tools\solid-telekram\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting core-js:
> https://opencollective.com/core-js
> https://patreon.com/zloirock
> https://boosty.to/zloirock
> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz

I highly recommend reading this: https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md

npm WARN notsup Unsupported engine for solid-qr-code@0.1.11: wanted: {"node":">=18"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: solid-qr-code@0.1.11
npm WARN notsup Unsupported engine for sass@1.77.6: wanted: {"node":">=14.0.0"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: sass@1.77.6
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup Unsupported engine for jsdom@24.1.3: wanted: {"node":">=18"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: jsdom@24.1.3
npm WARN notsup Unsupported engine for vite@5.2.0: wanted: {"node":"^18.0.0 || >=20.0.0"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: vite@5.2.0
npm WARN notsup Unsupported engine for typescript@5.7.2: wanted: {"node":">=14.17"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: typescript@5.7.2
npm WARN notsup Unsupported engine for whatwg-url@14.1.0: wanted: {"node":">=18"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: whatwg-url@14.1.0
npm WARN notsup Unsupported engine for cssstyle@4.1.0: wanted: {"node":">=18"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: cssstyle@4.1.0
npm WARN notsup Unsupported engine for data-urls@5.0.0: wanted: {"node":">=18"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: data-urls@5.0.0
npm WARN notsup Unsupported engine for saxes@6.0.0: wanted: {"node":">=v12.22.7"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: saxes@6.0.0
npm WARN notsup Unsupported engine for whatwg-encoding@3.1.1: wanted: {"node":">=18"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: whatwg-encoding@3.1.1
npm WARN notsup Unsupported engine for whatwg-mimetype@4.0.0: wanted: {"node":">=18"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: whatwg-mimetype@4.0.0
npm WARN notsup Unsupported engine for http-proxy-agent@7.0.2: wanted: {"node":">= 14"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: http-proxy-agent@7.0.2
npm WARN notsup Unsupported engine for w3c-xmlserializer@5.0.0: wanted: {"node":">=18"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: w3c-xmlserializer@5.0.0
npm WARN notsup Unsupported engine for https-proxy-agent@7.0.6: wanted: {"node":">= 14"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: https-proxy-agent@7.0.6
npm WARN notsup Unsupported engine for xml-name-validator@5.0.0: wanted: {"node":">=18"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: xml-name-validator@5.0.0
npm WARN notsup Unsupported engine for html-encoding-sniffer@4.0.0: wanted: {"node":">=18"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: html-encoding-sniffer@4.0.0
npm WARN notsup Unsupported engine for tr46@5.0.0: wanted: {"node":">=18"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: tr46@5.0.0
npm WARN notsup Unsupported engine for agent-base@7.1.3: wanted: {"node":">= 14"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: agent-base@7.1.3
npm WARN notsup Unsupported engine for rollup@4.29.1: wanted: {"npm":">=8.0.0","node":">=18.0.0"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: rollup@4.29.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/android-arm@0.20.2 (node_modules\esbuild\node_modules\@esbuild\android-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/android-arm@0.20.2: wanted {"os":"android","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/darwin-x64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/darwin-x64@0.20.2: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/netbsd-x64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\netbsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/netbsd-x64@0.20.2: wanted {"os":"netbsd","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/sunos-x64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\sunos-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/sunos-x64@0.20.2: wanted {"os":"sunos","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-x64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-x64@0.20.2: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/freebsd-x64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\freebsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/freebsd-x64@0.20.2: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-arm@0.20.2 (node_modules\esbuild\node_modules\@esbuild\linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-arm@0.20.2: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/android-x64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\android-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/android-x64@0.20.2: wanted {"os":"android","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-ia32@0.20.2 (node_modules\esbuild\node_modules\@esbuild\linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-ia32@0.20.2: wanted {"os":"linux","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/win32-ia32@0.20.2 (node_modules\esbuild\node_modules\@esbuild\win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/win32-ia32@0.20.2: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-arm64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-arm64@0.20.2: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-s390x@0.20.2 (node_modules\esbuild\node_modules\@esbuild\linux-s390x):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-s390x@0.20.2: wanted {"os":"linux","arch":"s390x"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-ppc64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\linux-ppc64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-ppc64@0.20.2: wanted {"os":"linux","arch":"ppc64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/android-arm64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/android-arm64@0.20.2: wanted {"os":"android","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/aix-ppc64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\aix-ppc64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/aix-ppc64@0.20.2: wanted {"os":"aix","arch":"ppc64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-loong64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\linux-loong64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-loong64@0.20.2: wanted {"os":"linux","arch":"loong64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/darwin-arm64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/darwin-arm64@0.20.2: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/openbsd-x64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\openbsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/openbsd-x64@0.20.2: wanted {"os":"openbsd","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/win32-arm64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\win32-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/win32-arm64@0.20.2: wanted {"os":"win32","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-mips64el@0.20.2 (node_modules\esbuild\node_modules\@esbuild\linux-mips64el):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-mips64el@0.20.2: wanted {"os":"linux","arch":"mips64el"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-riscv64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\linux-riscv64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-riscv64@0.20.2: wanted {"os":"linux","arch":"riscv64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/freebsd-arm64@0.20.2 (node_modules\esbuild\node_modules\@esbuild\freebsd-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/freebsd-arm64@0.20.2: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-freebsd-arm64@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-freebsd-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-freebsd-arm64@4.29.1: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-freebsd-x64@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-freebsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-freebsd-x64@4.29.1: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-darwin-arm64@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-darwin-arm64@4.29.1: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-android-arm64@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-android-arm64@4.29.1: wanted {"os":"android","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-linux-s390x-gnu@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-linux-s390x-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-linux-s390x-gnu@4.29.1: wanted {"os":"linux","arch":"s390x"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-darwin-x64@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-darwin-x64@4.29.1: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-linux-arm64-musl@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-linux-arm64-musl@4.29.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-linux-x64-musl@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-linux-x64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-linux-x64-musl@4.29.1: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-linux-arm-gnueabihf@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-linux-arm-gnueabihf):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-linux-arm-gnueabihf@4.29.1: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-linux-x64-gnu@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-linux-x64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-linux-x64-gnu@4.29.1: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-android-arm-eabi@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-android-arm-eabi):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-android-arm-eabi@4.29.1: wanted {"os":"android","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-linux-arm-musleabihf@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-linux-arm-musleabihf):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-linux-arm-musleabihf@4.29.1: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-linux-powerpc64le-gnu@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-linux-powerpc64le-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-linux-powerpc64le-gnu@4.29.1: wanted {"os":"linux","arch":"ppc64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-win32-arm64-msvc@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-win32-arm64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-win32-arm64-msvc@4.29.1: wanted {"os":"win32","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-linux-riscv64-gnu@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-linux-riscv64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-linux-riscv64-gnu@4.29.1: wanted {"os":"linux","arch":"riscv64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-win32-ia32-msvc@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-win32-ia32-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-win32-ia32-msvc@4.29.1: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-linux-loongarch64-gnu@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-linux-loongarch64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-linux-loongarch64-gnu@4.29.1: wanted {"os":"linux","arch":"loong64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @rollup/rollup-linux-arm64-gnu@4.29.1 (node_modules\rollup\node_modules\@rollup\rollup-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @rollup/rollup-linux-arm64-gnu@4.29.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup Unsupported engine for svgo@3.3.2: wanted: {"node":">=14.0.0"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: svgo@3.3.2
npm WARN notsup Unsupported engine for css-tree@2.3.1: wanted: {"node":"^10 || ^12.20.0 || ^14.13.0 || >=15.0.0"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: css-tree@2.3.1
npm WARN notsup Unsupported engine for csso@5.0.5: wanted: {"node":"^10 || ^12.20.0 || ^14.13.0 || >=15.0.0","npm":">=7.0.0"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: csso@5.0.5
npm WARN notsup Unsupported engine for css-tree@2.2.1: wanted: {"npm":">=7.0.0","node":"^10 || ^12.20.0 || ^14.13.0 || >=15.0.0"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: css-tree@2.2.1
npm WARN notsup Unsupported engine for tsconfck@3.1.4: wanted: {"node":"^18 || >=20"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: tsconfck@3.1.4

removed 1 package, updated 219 packages and audited 262 packages in 148.835s

27 packages are looking for funding
  run `npm fund` for details

found 3 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\Me\Downloads\platform-tools\solid-telekram>bun run build
$ vite build
(node:1748) ExperimentalWarning: The ESM module loader is experimental.
file:///C:/Users/Me/Downloads/platform-tools/solid-telekram/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:88:18)
    at async link (internal/modules/esm/module_job.js:41:21)
error: script "build" exited with code 1

```

</details>

I created a different environment with the latest `node` and then ran `bun run build` successfully. However, the build lacks support for selecting GIFs via attachments. The documentation screenshot for this project shows options for Emoji, Photo, Video, GIF, Contacts, Audio, Voice Message and Location. However, on my instance of Telekram (on KaiOS 2.5), options for GIF, Contacts, Audio, and Location are still missing.

Additionally, clicking on any URL or clickable content in a message freezes KaiOS 2.5, requiring a battery pull to restore functionality.

Any additional tips on how to fix this or what I might be missing?

**Comment by cyan-2048** [comment]
it is missing because I haven't implemented it yet, you can read the README to actually see the features that are present/missing, I am currently not updating the app as it is New Years Day and I am currently waiting for the latest version of mtcute (the mtproto telegram library I use) to escape pre-release, as I plan to rewrite the entire app from the ground up.

**Comment by jazz-it** [comment]
Your README is a bit ambiguous because, under Features, you’ve explicitly marked that this feature is not implemented. However, in the screenshots, selecting GIFs is clearly visible, so it wasn’t clear to me which information is outdated.

I hope the newer app will address these critical issues when opening links, which currently result in KaiOS completely unresponsive. Good luck! :)
